-- PostgreSQL 15+.
-- Surrogate and natural keys in a customer, order, and source-reconciliation
-- system. The surrogate customer ID is the stable relational identity.
-- Natural identifiers and external source identifiers have independent
-- uniqueness rules because they represent different business contracts.

BEGIN;

CREATE SCHEMA IF NOT EXISTS key_design_lab;
SET LOCAL search_path TO key_design_lab, public;

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    legal_name TEXT NOT NULL CHECK (length(btrim(legal_name)) > 0),
    country_code CHAR(2) NOT NULL
        CHECK (country_code ~ '^[A-Z]{2}$'),
    tax_identifier TEXT NOT NULL
        CHECK (length(btrim(tax_identifier)) > 0),
    email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- The pair is a natural key only if the applicable jurisdiction
    -- guarantees uniqueness. It remains a candidate key even though the
    -- surrogate primary key is used by dependent tables.
    CONSTRAINT uq_customer_tax_identity
        UNIQUE (country_code, tax_identifier),

    CONSTRAINT uq_customer_email
        UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS customer_external_ids (
    external_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL
        REFERENCES customers(customer_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    source_system TEXT NOT NULL
        CHECK (length(btrim(source_system)) > 0),
    source_record_id TEXT NOT NULL
        CHECK (length(btrim(source_record_id)) > 0),
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- The source-system/record pair identifies a record in its own system.
    -- It is not the same as the internal customer identity.
    CONSTRAINT uq_external_customer_source
        UNIQUE (source_system, source_record_id)
);

CREATE TABLE IF NOT EXISTS orders (
    order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id BIGINT NOT NULL
        REFERENCES customers(customer_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    source_system TEXT NOT NULL,
    source_order_id TEXT NOT NULL,
    amount_minor_units BIGINT NOT NULL
        CHECK (amount_minor_units >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_order_source
        UNIQUE (source_system, source_order_id),

    CONSTRAINT ck_order_source_nonempty
        CHECK (
            length(btrim(source_system)) > 0
            AND length(btrim(source_order_id)) > 0
        )
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_created
    ON orders (customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_external_ids_customer
    ON customer_external_ids (customer_id);

CREATE TABLE IF NOT EXISTS customer_key_audit (
    audit_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    old_country_code CHAR(2) NOT NULL,
    old_tax_identifier TEXT NOT NULL,
    new_country_code CHAR(2) NOT NULL,
    new_tax_identifier TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    change_reason TEXT NOT NULL
        CHECK (length(btrim(change_reason)) > 0)
);

CREATE OR REPLACE FUNCTION audit_customer_natural_key_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.country_code IS DISTINCT FROM NEW.country_code
       OR OLD.tax_identifier IS DISTINCT FROM NEW.tax_identifier THEN

        INSERT INTO customer_key_audit (
            customer_id,
            old_country_code,
            old_tax_identifier,
            new_country_code,
            new_tax_identifier,
            change_reason
        )
        VALUES (
            OLD.customer_id,
            OLD.country_code,
            OLD.tax_identifier,
            NEW.country_code,
            NEW.tax_identifier,
            'Natural-key correction recorded by database trigger'
        );
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_audit_customer_natural_key
    ON customers;

CREATE TRIGGER trg_audit_customer_natural_key
AFTER UPDATE OF country_code, tax_identifier ON customers
FOR EACH ROW
EXECUTE FUNCTION audit_customer_natural_key_change();

-- The following records use a deterministic, repeatable seed order.
-- Identity values are generated by PostgreSQL rather than supplied by clients.

INSERT INTO customers (
    legal_name, country_code, tax_identifier, email
)
VALUES
    ('Northern Industrial Supplies', 'IN', 'GST-29-ACME-001',
     'accounts@northern.example'),
    ('Western Components LLC', 'US', 'EIN-12-3456789',
     'finance@western.example'),
    ('Eastern Logistics GmbH', 'DE', 'VAT-DE-123456789',
     'billing@eastern.example')
ON CONFLICT (country_code, tax_identifier) DO NOTHING;

INSERT INTO customer_external_ids (
    customer_id, source_system, source_record_id
)
SELECT customer_id, 'erp-east', 'CUST-0044'
FROM customers
WHERE country_code = 'IN'
  AND tax_identifier = 'GST-29-ACME-001'
ON CONFLICT (source_system, source_record_id) DO NOTHING;

INSERT INTO customer_external_ids (
    customer_id, source_system, source_record_id
)
SELECT customer_id, 'erp-west', 'ACCT-209'
FROM customers
WHERE country_code = 'US'
  AND tax_identifier = 'EIN-12-3456789'
ON CONFLICT (source_system, source_record_id) DO NOTHING;

INSERT INTO orders (
    customer_id, source_system, source_order_id, amount_minor_units
)
SELECT customer_id, 'erp-east', 'ORDER-8801', 720050
FROM customers
WHERE country_code = 'IN'
  AND tax_identifier = 'GST-29-ACME-001'
ON CONFLICT (source_system, source_order_id) DO NOTHING;

INSERT INTO orders (
    customer_id, source_system, source_order_id, amount_minor_units
)
SELECT customer_id, 'erp-east', 'ORDER-8802', 125000
FROM customers
WHERE country_code = 'IN'
  AND tax_identifier = 'GST-29-ACME-001'
ON CONFLICT (source_system, source_order_id) DO NOTHING;

-- A reporting query resolves the stable foreign key to mutable business data.
SELECT
    c.customer_id,
    c.legal_name,
    c.country_code,
    c.tax_identifier,
    o.order_id,
    o.source_system,
    o.source_order_id,
    o.amount_minor_units
FROM customers AS c
JOIN orders AS o
    ON o.customer_id = c.customer_id
ORDER BY c.customer_id, o.source_order_id;

-- Compare the number of internal customers with the number of external
-- identities. One customer may legitimately have identities in many systems.
SELECT
    c.customer_id,
    c.legal_name,
    COUNT(e.external_id) AS external_identity_count
FROM customers AS c
LEFT JOIN customer_external_ids AS e
    ON e.customer_id = c.customer_id
GROUP BY c.customer_id, c.legal_name
ORDER BY c.customer_id;

-- Detect duplicate natural identifiers in an imported staging dataset
-- before attempting insertion into the constrained master table.
WITH incoming_tax_records(country_code, tax_identifier, legal_name) AS (
    VALUES
        ('IN', 'GST-29-ACME-001', 'Duplicate Imported Record'),
        ('IN', 'GST-29-ACME-777', 'New Imported Entity'),
        ('US', 'EIN-12-3456789', 'Existing US Entity')
)
SELECT
    country_code,
    tax_identifier,
    COUNT(*) AS source_row_count,
    ARRAY_AGG(legal_name ORDER BY legal_name) AS names
FROM incoming_tax_records
GROUP BY country_code, tax_identifier
HAVING COUNT(*) > 1;

-- Find natural-key collisions between incoming records and the master table.
WITH incoming_tax_records(country_code, tax_identifier, legal_name) AS (
    VALUES
        ('IN', 'GST-29-ACME-001', 'Duplicate Imported Record'),
        ('IN', 'GST-29-ACME-777', 'New Imported Entity'),
        ('US', 'EIN-12-3456789', 'Existing US Entity')
)
SELECT
    i.country_code,
    i.tax_identifier,
    i.legal_name AS incoming_name,
    c.customer_id,
    c.legal_name AS existing_name
FROM incoming_tax_records AS i
JOIN customers AS c
    ON c.country_code = i.country_code
   AND c.tax_identifier = i.tax_identifier
ORDER BY i.country_code, i.tax_identifier;

-- Demonstrate a natural-key correction without changing customer_id.
-- The trigger records the old and new business identity in the audit table.
UPDATE customers
SET tax_identifier = 'GST-29-ACME-009'
WHERE country_code = 'IN'
  AND tax_identifier = 'GST-29-ACME-001';

SELECT
    customer_id,
    legal_name,
    country_code,
    tax_identifier
FROM customers
WHERE country_code = 'IN';

SELECT *
FROM customer_key_audit
ORDER BY audit_id;

-- Merge eligibility is not a database-key concern, but the same principle
-- applies: keep independently meaningful identities in separate columns.
-- The query below verifies source-key uniqueness and referential integrity.
SELECT
    o.source_system,
    o.source_order_id,
    COUNT(*) AS order_count,
    COUNT(DISTINCT o.customer_id) AS distinct_customers
FROM orders AS o
GROUP BY o.source_system, o.source_order_id
HAVING COUNT(*) > 1
    OR COUNT(DISTINCT o.customer_id) > 1;

COMMIT;

-- Expected integrity failures, intentionally commented out so the entire
-- script remains executable:
--
-- Duplicate natural key:
-- INSERT INTO key_design_lab.customers
--     (legal_name, country_code, tax_identifier)
-- VALUES ('Collision', 'US', 'EIN-12-3456789');
--
-- Invalid foreign key:
-- INSERT INTO key_design_lab.orders
--     (customer_id, source_system, source_order_id, amount_minor_units)
-- VALUES (9223372036854770000, 'erp-east', 'ORDER-BAD', 100);
--
-- Duplicate source order:
-- INSERT INTO key_design_lab.orders
--     (customer_id, source_system, source_order_id, amount_minor_units)
-- SELECT customer_id, 'erp-east', 'ORDER-8801', 1
-- FROM key_design_lab.customers
-- WHERE country_code = 'IN';
--
-- The primary key, unique constraints, foreign keys, and check constraints
-- enforce distinct rules. Application validation alone cannot replace them.
