-- PostgreSQL 15+
-- Safe schema evolution: versioned contracts, backfills, compatibility,
-- migration history, and transactional enforcement.

BEGIN;

CREATE SCHEMA IF NOT EXISTS evolution_lab;
SET search_path TO evolution_lab, public;

CREATE TABLE IF NOT EXISTS schema_versions (
    version INTEGER PRIMARY KEY CHECK (version > 0),
    description TEXT NOT NULL,
    checksum TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS migration_events (
    event_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    from_version INTEGER NOT NULL,
    to_version INTEGER NOT NULL,
    event_type TEXT NOT NULL CHECK (
        event_type IN ('registered', 'backfilled', 'enforced', 'contracted')
    ),
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (to_version >= from_version)
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL CHECK (length(trim(full_name)) > 0),
    email TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_versions(version, description, checksum)
VALUES (1, 'Initial customer identity schema', 'customers-v1')
ON CONFLICT (version) DO NOTHING;

INSERT INTO customers(customer_id, full_name, email)
VALUES
    (1001, 'Asha Sharma', 'asha@example.com'),
    (1002, 'Rohan Mehta', NULL),
    (1003, 'Priya Nair', 'priya@example.com')
ON CONFLICT (customer_id) DO NOTHING;

INSERT INTO migration_events(from_version, to_version, event_type, details)
VALUES (1, 1, 'registered', '{"phase":"initial"}'::jsonb);

COMMIT;

-- Expansion: add new columns without immediately requiring values from
-- legacy writers. Nullable columns permit mixed application versions.
ALTER TABLE evolution_lab.customers
    ADD COLUMN IF NOT EXISTS phone_number TEXT;

ALTER TABLE evolution_lab.customers
    ADD COLUMN IF NOT EXISTS country_code TEXT;

INSERT INTO evolution_lab.schema_versions(version, description, checksum)
VALUES (2, 'Expand customer contact and country fields', 'customers-v2')
ON CONFLICT (version) DO NOTHING;

INSERT INTO evolution_lab.migration_events(
    from_version, to_version, event_type, details
)
VALUES (
    1, 2, 'registered',
    '{"strategy":"expand","nullable_columns":["phone_number","country_code"]}'::jsonb
);

-- Backfill in a bounded, repeatable operation. Production migrations should
-- process large tables in batches to control locks and replication lag.
UPDATE evolution_lab.customers
SET country_code = 'IN'
WHERE country_code IS NULL;

UPDATE evolution_lab.customers
SET email = lower(trim(email))
WHERE email IS NOT NULL
  AND email <> lower(trim(email));

INSERT INTO evolution_lab.migration_events(
    from_version, to_version, event_type, details
)
VALUES (
    2, 2, 'backfilled',
    jsonb_build_object(
        'rows_missing_country',
        (SELECT count(*) FROM evolution_lab.customers
         WHERE country_code IS NULL),
        'rows_missing_email',
        (SELECT count(*) FROM evolution_lab.customers
         WHERE email IS NULL)
    )
);

-- Inspect data quality before enforcing the new contract. NULL emails are
-- deliberately reported rather than assigned fabricated addresses.
SELECT customer_id, full_name
FROM evolution_lab.customers
WHERE email IS NULL
ORDER BY customer_id;

SELECT country_code, count(*) AS customer_count
FROM evolution_lab.customers
GROUP BY country_code
ORDER BY country_code;

CREATE INDEX IF NOT EXISTS idx_customers_country_created
    ON evolution_lab.customers(country_code, created_at DESC);

-- Use NOT VALID to install a constraint without scanning all existing rows
-- immediately. VALIDATE CONSTRAINT performs the historical data check.
ALTER TABLE evolution_lab.customers
    ADD CONSTRAINT customers_country_code_format
    CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$')
    NOT VALID;

ALTER TABLE evolution_lab.customers
    VALIDATE CONSTRAINT customers_country_code_format;

-- Enforce country_code after confirming the backfill has completed.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM evolution_lab.customers
        WHERE country_code IS NULL
    ) THEN
        RAISE EXCEPTION 'Cannot enforce country_code: backfill is incomplete';
    END IF;
END;
$$;

ALTER TABLE evolution_lab.customers
    ALTER COLUMN country_code SET DEFAULT 'IN';

ALTER TABLE evolution_lab.customers
    ALTER COLUMN country_code SET NOT NULL;

INSERT INTO evolution_lab.schema_versions(version, description, checksum)
VALUES (3, 'Validate and enforce country code', 'customers-v3')
ON CONFLICT (version) DO NOTHING;

INSERT INTO evolution_lab.migration_events(
    from_version, to_version, event_type, details
)
VALUES (
    2, 3, 'enforced',
    '{"required_field":"country_code","constraint":"customers_country_code_format"}'::jsonb
);

-- A new application-facing view gives consumers a stable projection while
-- the underlying storage schema continues to evolve.
CREATE OR REPLACE VIEW evolution_lab.customer_directory AS
SELECT
    customer_id,
    full_name AS display_name,
    email,
    country_code,
    created_at
FROM evolution_lab.customers;

-- Demonstrate a controlled rename through an expand-and-contract strategy.
-- The old column remains available while clients adopt display_name.
ALTER TABLE evolution_lab.customers
    ADD COLUMN IF NOT EXISTS display_name TEXT;

UPDATE evolution_lab.customers
SET display_name = full_name
WHERE display_name IS NULL;

ALTER TABLE evolution_lab.customers
    ALTER COLUMN display_name SET NOT NULL;

ALTER TABLE evolution_lab.customers
    ADD CONSTRAINT customers_display_name_nonempty
    CHECK (length(trim(display_name)) > 0)
    NOT VALID;

ALTER TABLE evolution_lab.customers
    VALIDATE CONSTRAINT customers_display_name_nonempty;

CREATE OR REPLACE VIEW evolution_lab.customer_directory AS
SELECT
    customer_id,
    display_name,
    email,
    country_code,
    created_at
FROM evolution_lab.customers;

INSERT INTO evolution_lab.schema_versions(version, description, checksum)
VALUES (4, 'Introduce validated display name projection', 'customers-v4')
ON CONFLICT (version) DO NOTHING;

INSERT INTO evolution_lab.migration_events(
    from_version, to_version, event_type, details
)
VALUES (
    3, 4, 'registered',
    '{"strategy":"expand-contract","legacy_column":"full_name"}'::jsonb
);

-- Inspect the effective schema contract and historical migration sequence.
SELECT
    version,
    description,
    checksum,
    applied_at
FROM evolution_lab.schema_versions
ORDER BY version;

SELECT
    event_id,
    from_version,
    to_version,
    event_type,
    details,
    occurred_at
FROM evolution_lab.migration_events
ORDER BY event_id;

SELECT *
FROM evolution_lab.customer_directory
ORDER BY customer_id;

-- Demonstrate transaction-level rollback. The invalid country value violates
-- the check constraint; the savepoint preserves earlier work in the session.
BEGIN;

SAVEPOINT before_invalid_write;

DO $$
BEGIN
    BEGIN
        INSERT INTO evolution_lab.customers(
            customer_id, full_name, email, country_code, display_name
        )
        VALUES (
            9001, 'Invalid Country', 'invalid@example.com', 'IND', 'Invalid Country'
        );
    EXCEPTION
        WHEN check_violation THEN
            RAISE NOTICE 'Rejected invalid country code as expected';
    END;
END;
$$;

ROLLBACK TO SAVEPOINT before_invalid_write;
ROLLBACK;

-- This query should return zero because the failed write did not persist.
SELECT count(*) AS rejected_record_count
FROM evolution_lab.customers
WHERE customer_id = 9001;

-- Contracting is intentionally not performed automatically here.
-- Drop legacy columns only after all deployed readers and writers have moved
-- to display_name and the rollback window has expired.
-- ALTER TABLE evolution_lab.customers DROP COLUMN full_name;
